spring:
  application:
    name: hr-api-gateway-zuul
server:
  port: 8765

hr-worker:
  ribbon:
    ConnectTimeout: 10000
    ReadTimeout: 20000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    worker:
      path: /hr-worker/**
      serviceId: hr-worker
    payroll:
      path: /hr-payroll/**
      serviceId: hr-payroll