spring:
  datasource:
    url: jdbc:mysql://jay.com.br:3306/jay_teste?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimeZone=UTC
    username: jay_teste_user
    password: q9}2WJ}X&BYt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false

security:
  jwt:
    expiracao: 30
    chave-assinatura: YSBsZWJyZSDDqSBicmFuY2E=